### ISSUE TITLE
Add logging to config example

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#1536]
The current example config comes without logging config which we should avoid and add:

```yml
logging:
  level: INFO

  loggers:
    "com.graphhopper": INFO

  appenders:
    - type: file
      timeZone: UTC
      currentLogFilename: logs/graphhopper.log
      logFormat: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      archive: true
      archivedLogFilenamePattern: ./logs/graphhopper-%d.log.gz
      archivedFileCount: 30
    - type: console
      timeZone: UTC
      logFormat: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
```
