### ISSUE TITLE
Allow cross-querying weightings for hybrid mode

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#1980]
Currently we can prepare a profile for hybrid mode (calculate landmarks). The weighting we use with these landmarks does not necessarily have to be the same as the one we used for the preparation. We can use any weighting as long as all edge weights calculated with this weighting are equal or larger in weight than the ones used during the preparation. So it would be useful to be able to 'cross-query': Use some existing landmarks with a weighting other than the one that was used during preparation.

Maybe we can do it like this:

```yaml
profiles:
  - name: my_car
    vehicle: car
    weighting: some_weighting
  - name: my_adjusted_car
    vehicle: car
    weighting: other_weighting
lm_profiles:
   # this means we will calculate landmarks for the 'my_car' profile
  - name: my_car 
  # this means we do *not* calculate landmarks for the 'my_adjusted_car', but we can use still use 
  # the 'my_adjusted_car' profile in hybrid mode and it will use the landmarks from the 'my_car' profile
  - name: my_adjusted_car
    landmarks: my_car
```

The route calculation will only be correct if all edge-weights returned by `other_weighting` are equal or larger than those returned from `some_weighting`.
