### ISSUE TITLE
SPT with finite, non-zero turn costs much slower

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper#2086]
For routing with turn restrictions enabled we have a slow down of approx. 2x and so I would expect a maximum slow down of 2x (because the shortest path exploration is usually the fast part of the isochrone calculation). But it seems that the slow down factor is over 6x even for smaller time limits like 10min:

```
time curl 'localhost:8989/isochrone?point=52.550732,13.350878&profile=car&time_limit=600'
...
real	0m1,179s
user	0m0,000s
sys	0m0,018s

time curl 'localhost:8989/isochrone?point=52.550732,13.350878&profile=car_no_tc&time_limit=600'
...
real	0m7,464s
user	0m0,010s
sys	0m0,004s
```

Related to #1978 and #1458.

**Comment by karussell** [comment]
Strange. I cannot reproduce this on my local machine (4.5s vs. 2.8s). Closing for now.

**Comment by easbar** [comment]
Keep in mind that if turn costs are enabled the graph exploration is edge-based and so the shortest path tree is larger (contains edges that otherwise would be skipped as they point to already explored nodes). Maybe this could be an explanation? 

See this: https://discuss.graphhopper.com/t/missing-edges-in-spt-response/5586/4

**Comment by otbutz** [comment]
You could profile the execution using JFR if you're using Java 11 or higher.

JMC: https://adoptopenjdk.net/jmc.html

**Comment by easbar** [comment]
> the resulting shape is only slightly different

Yeah but the shortest path trees could still be very different in size? In your example the number of visited nodes is very different (486191 for car vs 170438 for car_no_tc) so to me it seems like the real question is why in one case much less nodes are explored (could be due to better/worse LM heuristic?). Maybe MiniGraphUI could help here :)

**Comment by michaz** [comment]
Hmm. Seems elusive. Works fine on my machine.

```
2020-07-22 10:44:11.757 [dw-21 - GET /isochrone?point=48.839413,2.351074&profile=car_no_tc&time_limit=400] INFO  c.g.resources.IsochroneResource - took: 1.1765695, visited nodes:170247, consumed nodes:21612, {time_limit=[400], profile=[car_no_tc], point=[48.839413,2.351074]}
2020-07-22 10:44:19.128 [dw-20 - GET /isochrone?point=48.839413,2.351074&profile=car&time_limit=400] INFO  c.g.resources.IsochroneResource - took: 2.435008, visited nodes:432537, consumed nodes:36972, {time_limit=[400], profile=[car], point=[48.839413,2.351074]}

```

**Comment by michaz** [comment]
Am I doing this right?

```
  datareader.file: ile-de-france-latest.osm.pbf
  graph.flag_encoders: car|turn_costs=true
  graph.location: graphs/ile-de-france/graph
  profiles:
    - name: car_no_tc
      vehicle: car
      weighting: fastest
      turn_costs: false
    - name: car
      vehicle: car
      weighting: fastest
      turn_costs: true
```
