### ISSUE TITLE
Turn costs get ignored for custom weighting

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2176]
From here: https://discuss.graphhopper.com/t/custom-model-uses-not-allowed-turn/6124/

When we use something like: 

```yaml
profiles:
   - name: car
   - vehicle: car
   - turn_costs: true
   - weighting: custom
   - custom_model_file: empty
```

the `turn_costs: true` setting is simply ignored, i.e. we cannot use turn costs with custom weightings. I'm surprised we did not notice this earlier?!
