### ISSUE TITLE
Cannot use any timezone in ISO ISO-8601 format for pt.departure_time

### ISSUE THREAD

**Issue by ainar** [graphhopper/graphhopper#2490]
**Describe the bug**
If we use another time zone than UTC, it throws an error. More precisely, this is not even UTC that is only allowed, as "+00:00" also throws an error, but only "Z".

**To Reproduce**

1. checkout most recent version of GraphHopper and compile it
2. download OSM data and a GTFS archive (for example [this OSM data](http://download.geofabrik.de/europe/france/rhone-alpes-211206.osm.pbf) and [this GTFS](https://www.mobilites-m.fr/data/Horaires/SEM-GTFS.zip))
3. create the config.yml file with the content below

<details>
<summary>config.yml</summary>

```yaml
graphhopper:
  datareader.file: path/to/rhone-alpes-211206.osm.pbf
  graph.location: graph-cache
  gtfs.file: path/to/SEM-GTFS.zip
  prepare.min_network_size: 1000

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: car
      vehicle: car
      weighting: fastest
    - name: bike
      vehicle: bike
      weighting: fastest
    - name: motorcycle
      vehicle: motorcycle
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
```
</details>

4. run `java  -jar path/to/graphhopper-web-5.0-SNAPSHOT.jar server config.yml`
5. Get any `pt` itinerary with `pt.earliest_departure_time` set on another time zone than "Z", for example `GET http://localhost:8989/route?point=45.212036%2C5.690918&point=45.166547%2C5.776749&locale=fr&pt.earliest_departure_time=2021-12-10T14%3A10%3A00+01%3A00&profile=pt`

**Expected behavior**
As explained by the documentation and the error message below, the parameter should accept any valid ISO-8601 date.

**System Information**
- Ubuntu 21.10
- openjdk version "11.0.12" 2021-07-20
- GraphHopper https://github.com/graphhopper/graphhopper/commit/fbcdd6a4d3cc4a7cc9c0a6148e7dfeacd1abf7cc

**Screenshots & Logs**
The answer returned by the API:
```json
{"code":400,"message":"query param pt.earliest_departure_time must be in a ISO-8601 format."}
```

**Possible solutions**
- Explicitly say in documentation and error message that the date must be in UTC and ends with "Z" (and I think, probably like you, this is a terrible behaviour for multiple reasons).
- Allow other time zone to be set. Hint: use _java.time.ZonedDateTime_ instead of _Instant_ for this purpose, and cast it to _Instant_ only where it is needed. The purpose of _earliest_departure_time_ is much more consistent with the use of  _ZonedDateTime_ than _Instant_.

Moreover you can get rid of the currently deprecated _InstantParam_ by creating your own parameter class (by implementing _AbstractParam_), as now intended by jersey. https://github.com/graphhopper/graphhopper/blob/9bf683c41d97d919b96d7bf118561584fd440564/web-bundle/src/main/java/com/graphhopper/resources/PtRouteResource.java#L58
