### ISSUE TITLE
CH preparation for foot is too slow

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper#2507]
Unfortunately #2491 introduced a performance regression for the CH preparation of the foot profile. It used to take around 630s and for current master it takes more than 2000s. I recently added a performance measurement for foot here: 1ec3397bfb832f07202136f00dc81182fa5896aa, 92842baaf07f3d81cbf5925b104db51713417aaa. The query time seems unaffected for our test map of Germany but turned out to be also slower when using an OSM file of the entire planet.

The current workaround is to disable neighbor updates and increase the maximum of visited nodes, i.e. in config.yml use the following parameters:

```yaml
  prepare.ch.node.max_visited_nodes_heuristic: 200
  prepare.ch.node.max_visited_nodes_contraction: 500
  prepare.ch.updates.periodic: 20
  prepare.ch.updates.lazy: 100
  prepare.ch.updates.neighbor: 0
```

Unfortunately this slows down the CH preparation for car and increases the number of shortcuts compared to the current default parameters. 

Two things we could do to improve this:

1) limit the maximum number of neighbor updates per node
2) make the number of maximum visited nodes depend on the mean degree of the graph again as we used to do (but without the bugs we fixed in #2491)

Another option might be to allow setting these parameters per profile, but currently I'd prefer a solution that works reasonably well for all profiles.
