### ISSUE TITLE
Cannot get some public transport itineraries

### ISSUE THREAD

**Issue by ainar** [graphhopper/graphhopper#2518]
**Description**
For some origins and destinations, the paths are empty (undefined behavior). See the log below.

It worked before the commit b038bfcd1d5823a2f208dff00f87fdc539d7eaed. I do not know exactly what is happening. If you change a bit the origin and destination (for origin, for example 45.361,5.950), it successfully find paths. @michaz if you explain what you changed, we may be able to figure it out.

**To Reproduce**

1. checkout GraphHopper and build
2. use the configuration below with the files [PBF](https://fromsmash.com/fzfjMOwfCh-ct) and [GTFS](https://github.com/ainar/files/raw/3c4881cef0132b4ce95d7034639e61af2e33c99f/40ee9d6c-3bb9-409e-b670-986212de63f2_CG38.GTFS.zip) (it may also work with [updated PBF](https://download.geofabrik.de/europe/france/rhone-alpes-latest.osm.pbf))
4. run `java -Xmx32G  -jar path to /web/target/graphhopper-web-5.0-SNAPSHOT.jar server config_ara_tc.yml`
5. Go to http://localhost:8989/route?point=45.360,5.950&point=45.180,5.740&profile=pt&pt.arrive_by=false&pt.earliest_departure_time=2022-01-05T16:40:00Z

Minimum configuration:
```yaml
graphhopper:
  datareader.file: /path to/rhone-alpes-latest.osm.pbf
  graph.location: graph-cache-ara-tc
  gtfs.file: /path to /40ee9d6c-3bb9-409e-b670-986212de63f2_CG38.GTFS.zip

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
```

**Expected behavior**
The paths should not be empty. There should be at least one path. (At least, an error should be written.)

**System Information**

- Ubuntu 21.10
- Java
    - openjdk version "11.0.13" 2021-10-19
    - OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.21.10)
    - OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.21.10, mixed mode, sharing)
- GraphHopper after commit b038bfcd1d5823a2f208dff00f87fdc539d7eaed

**Screenshots & Logs**

<details>
<summary>Output with a build after commit b038bfcd1d5823a2f208dff00f87fdc539d7eaed</summary>

```json
{
  "hints": {
    "visited_nodes.sum": 1351705,
    "visited_nodes.average": 1351705
  },
  "info": {
    "copyrights": [
      "GraphHopper",
      "OpenStreetMap contributors"
    ],
    "took": 1887
  },
  "paths": []
}
```
</details>

<details>
<summary>Output with a build before commit</summary>

```json
{
  "hints": {
    "visited_nodes.sum": 114067,
    "visited_nodes.average": 114067
  },
  "info": {
    "copyrights": [
      "GraphHopper",
      "OpenStreetMap contributors"
    ],
    "took": 289
  },
  "paths": [
    {
      "distance": 1626.231,
      "weight": 3103097,
      "time": 3103097,
      "transfers": 0,
      "points_encoded": false,
      "bbox": [
        5.737206,
        45.179985,
        5.955309,
        45.359999
      ],
      "points": {
        "type": "LineString",
...
```
</details>
