### ISSUE TITLE
Motorcycle profile speed section is ignored

### ISSUE THREAD

**Issue by NicholasRasi** [graphhopper/graphhopper#2908]
**Describe the bug**
When using the suggested [motorcycle profile](https://github.com/graphhopper/graphhopper/blob/8.x/core/src/main/resources/com/graphhopper/custom_models/motorcycle.json), the resulting route duration is incorrect. In my opinion, this line { "if": "true", "multiply_by": "0.9 * car_average_speed" } produces a wrong result (the base speed is multiplied by 90% of the car_average_speed). However, the main bug is that if I change the speed section to { "if": "true", "limit_to": "car_average_speed" }, the resulting route time does not change. Meanwhile, if I append another custom_model_files with only the speed section, it works correctly.

**To Reproduce**

Steps to reproduce the behavior.

1. checkout recent and stable version of GraphHopper v8
2. pbf https://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.pbf
3. `config.yml`
```
graphhopper:
  datareader.file: "/mnt/disk/GRAPHHOPPER/nord-ovest-latest.osm.pbf"
  graph.location: "/home/ubuntu/GRAPHHOPPER/graph-cache-2"

  graph.vehicles: roads|transportation_mode=MOTORCYCLE|turn_costs=true,car,bike,foot
  profiles:
      # Moto Street
      - name: motorcycle
        vehicle: roads
        weighting: custom
        turn_costs: true
        custom_model_files: [motorcycle.json]
  profiles_lm:
      - profile: motorcycle

  graph.encoded_values: average_slope,curvature,hike_rating,max_slope,max_width,mtb_rating,surface,toll,track_type
```

**Expected behavior**
I expect that I can change the speed section of the `motorcycle.json` file. It seems that the speed section of the first custom model file is ignored.

**System Information**
- Ubuntu 22
- Java 18
- GraphHopper v8.0
